sudo: required
services:
    - docker

before_install:
    - docker build  -t appa253/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true appa253/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    application: "Docker-React"
    env: "DockerReact-env"
    bucket: "elasticbeanstalk-ap-south-1-539062601900"
    on:
        branch: master
    access_key_id: "U19QQcju8lVfX42vpasItnDWe9Aa6D+aLxVRxy+A3Bs9w4Jboqitg9KGKvYnD4JpCyMXEee+qZk9zXnhwQMxFfFi9NjcKI0Xv5TaTK85vLC7mQY6kTqTMrz4PgOoNdfIxEXorrVYw87G5/gbL4OhMAp+jK32vCJzKy3CrARxmFo="
    secret_access_key:
        secure: "U19QQcju8lVfX42vpasItnDWe9Aa6D+aLxVRxy+A3Bs9w4Jboqitg9KGKvYnD4JpCyMXEee+qZk9zXnhwQMxFfFi9NjcKI0Xv5TaTK85vLC7mQY6kTqTMrz4PgOoNdfIxEXorrVYw87G5/gbL4OhMAp+jK32vCJzKy3CrARxmFo="