language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t appa253/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true appa253/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "myDockerApp"
  env: "Mydockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-539062601900"
  bucket_path: "myDockerApp"
  on:
    branch: master
  env:
    global:
      - secure:  $AWS_ACCESS_KEY
      - secure: $AWS_SECRET_KEY
