language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t appa253/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true appa253/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "myDockerReact"
  env: "Mydockerreact-env"
  bucket_name: "mydockerreact.s3.bucket"
  bucket_path: "myDockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY