sudo: required
services:
    - docker

before_install:
    - docker build  -t appa253/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true appa253/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "Docker-React"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-539062601900"
    bucket_path: ""Docker-React"
    access_key_id: "$AWS_ACCESS_KEY"