language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t appa253/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true appa253/docker-react npm run test

deploy:
  provider: s3
  bucket : "elasticbeanstalk-us-east-2-539062601900"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY