sudo: required
services:
    - docker

before_install:
    - docker build  -t appa253/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true appa253/docker-react npm run test

deploy:
    provider: s3
    region: "us-east-2"
    bucket: Docker-React
    access_key_id: "KKNPHHc2RQVk3y7O7qwpdeKsFeH2aeADRgKFTPrL"
    secret_access_key:
        secure: "KKNPHHc2RQVk3y7O7qwpdeKsFeH2aeADRgKFTPrL"